AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mountain Seed DataPoint Retrieval Service

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  DataPointFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.mountainseed.datapoint.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: ./target/datapoint-retrieval-service-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'

Outputs:
  SpringBootDataPointApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/dps'
    Export:
      Name: SpringBootDataPointApi
